version: '{build}'

environment:
  LINT: 0
  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
  CMAKE_PARAM: 'Visual Studio 15 2017 Win64'
  MUST_USE_TCPIP: 1
  matrix:
    - DB: '10.2.13'
      nodejs_version: "6"

    - DB: '10.2.13'
      nodejs_version: "8"

    - DB: '10.2.13'
      nodejs_version: "9"
      MYSQL_USE_COMPRESSION: 1

    - DB: '10.2.13'
      nodejs_version: "9"

    - DB: '10.2.13'
      nodejs_version: "9"
      BENCH: "1"

    - DB: '10.2.13'
      nodejs_version: "8"

    - DB: '10.3.4'
      nodejs_version: "8"

    - DB: '10.1.30'
      nodejs_version: "8"

    - DB: '10.0.33'
      nodejs_version: "8"

    - DB: '5.5.59'
      nodejs_version: "8"

cache:
  - node_modules
  - "%LOCALAPPDATA%/Yarn"
clone_folder: c:\projects\mariadb-connector-nodejs

install:
  - cmd: set FILE=http://mariadb.mirrors.ovh.net/MariaDB/mariadb-%DB%/winx64-packages/mariadb-%DB%-winx64.msi
  - ps: Start-FileDownload $Env:FILE -FileName server.msi
  - cmd: msiexec /i server.msi INSTALLDIR=c:\projects\server SERVICENAME=mariadb ALLOWREMOTEROOTACCESS=true /qn
  - cmd: "\"c:\\projects\\server\\bin\\mysql.exe\" -e \"create database testn\" --user=root"
  - ps: Install-Product node $env:nodejs_version
  - yarn install

build: off

test_script:
  - node --version
  - yarn --version
  - cd c:\projects\mariadb-connector-nodejs
  - if "%BENCH%" == "1" ( npm install microtime mariasql ) else ( npm test )
  - if "%BENCH%" == "1" ( yarn run benchmark )
